//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.GameData
{
	using GeneralPackage.Structures;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Agent
    {

        #region constructor

        internal Agent(Eventer eventHadler, int ID)
        {
            this.eventer = eventHadler;
            this.id = ID;
            coord = Coord.rand();
            speed = Average.speed;
            viewRadius = Average.viewRadius;
            type = AgentType.Dummy;
        }

        internal Agent(Eventer eventHandler, int ID, double speed, double viewRadius, Coord coord, 
                        AgentType type)
        {
            this.eventer = eventHandler;
            this.id = ID;
            this.speed = speed;
            this.coord = coord;
            this.viewRadius = viewRadius;
            this.type = type;
        }
           

        #endregion

        #region attributes


        public Eventer Eventer
        {
            get
            {
                return eventer;
            }
        }

		public Coord coord
		{
			get;
			set;
		}

		public double speed
		{
			get;
			set;
		}

		public int ID
		{
			get {
                return id;
            }
		}

		public double viewRadius
		{
			get;
			set;
		}

        public AgentType type {
            get;
            set;
        }

        private int id;
        private Eventer eventer;

        #endregion

        public void deleted()
        {
            eventer.deleted();
        }

        public AgentCutaway getCutaway()
        {
            return new AgentCutaway { ID = this.id, coord = this.coord, type = this.type };
        }
    }
}

