//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.GameData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Eventer
	{
        public virtual void ready () {
        }

        public virtual void deleted()
        {
        }

        #region StepByStep model

        public virtual void makeTurn()
        {
        }
        #endregion

    }
}

