//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.GameData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Structures;

	public class WallList
	{
        private List<Segment> list = new List<Segment>();
        internal bool changed = false;

        internal void addWall(Segment seg) {
            changed = true;
            list.Add(seg);
        }
        
        internal IReadOnlyCollection<Segment> getList() {
            changed = false;
            return list;
        }
	}
}

