//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Structures
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public struct Coord
    {

        #region attributes


        public double x
        {
            get;
            set;
        }

        public double y
        {
            get;
            set;
        }

        #endregion

        #region constructor

        #endregion

        public static Coord rand()
        {
            Random random = new Random();
            return new Coord
            {
                x = random.NextDouble(),
                y = random.NextDouble()
            };
                
        }


    }
}