//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GeneralPackage.Manager
{
	using GeneralPackage.Controller;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using GameData;
    using Controller;
    using Structures;
    using Performer;
    using Visualizer;

	public class Manager
    {

        #region attributes

        private Board board
		{
			get;
			set;
        }

        private CommandPerformer performer{
            get;
            set;
        }

        private Visualizer vizualizer
        {
            get;
            set;
        }

        #endregion

        #region constructor

        public Manager()
        {
            board = new Board();
            performer = new CommandPerformer(board);
        }
        


        #endregion

        #region adding agents

        public AgentController addCustomAgent(Coord startCoord, Eventer eventHandler,
                                    double speed, double viewRadius)
        {
            int ID;
            ID = board.Agents.addCustomAgent(startCoord, eventHandler, speed, viewRadius);
            return new AgentController(performer, ID);
        }

        public void addTestAgent()
        {
            board.Agents.addTestAgent();
        }
            

        #endregion

        #region vizualization

        public CommonFormVisualizer getFormVis(System.Windows.Forms.PictureBox screen)
        {
            return new CommonFormVisualizer(board, screen);
        }

        #endregion

        #region action-cycle

        public void launchAgents()
        {
            //allows each agent to do one action
            board.Agents.launchAgents();
        }

        #endregion
    }
}

